version: "3.9"
services:
  pihole:
    container_name: pihole
    build: ./dockerfiles/pihole/.
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Vienna'
      WEBPASSWORD: 'admin'
    volumes:
      - './volumes/pihole/etc-pihole:/etc/pihole'
      - './volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  squid:
    container_name: squid
    build: ./dockerfiles/squid/.
    ports:
      - "3128:3128/tcp"
      - "3128:3128/udp"
    volumes:
      - ./dockerfiles/squid/squid.conf:/etc/squid/squid.conf
    restart: unless-stopped
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:ubuntu
    mem_limit: 187m
    # network_mode: host
    ports:
      - "8581:8581/tcp"
      - "8581:8581/udp"
    environment:
      PGID: '1000'
      PUID: '1000'
      HOMEBRIDGE_CONFIG_UI: '1'
      HOMEBRIDGE_CONFIG_UI_PORT: '8581'
      TZ: 'Europe/Vienna'
    volumes:
      - ./volumes/homebridge:/homebridge
    restart: unless-stopped