version: "3"
services:

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000/tcp"
      - "3000:3000/udp"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090/tcp"
      - "9090:9090/udp"
    volumes:
      - ./volumes/prometheus:/etc/prometheus
    restart: unless-stopped

  # pihole:
  #   build: ./dockerfiles/pihole/.
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "67:67/udp"
  #     - "8080:80/tcp"
  #   environment:
  #     TZ: 'Europe/Vienna'
  #     WEBPASSWORD: 'admin'
  #   volumes:
  #     - ./volumes/pihole/etc:/etc/pihole
  #     - ./volumes/pihole/dns:/etc/dnsmasq.d
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped

  # loki:
  #   image: grafana/loki:latest
  #   ports:
  #     - "3100:3100/tcp"
  #     - "3100:3100/udp"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   restart: unless-stopped
